# Generated by Django 3.2.25 on 2026-01-27 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_basic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminotp',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='adminotp',
            name='otp_type',
            field=models.CharField(choices=[('LOGIN', 'Login OTP'), ('PASSWORD_RESET', 'Password Reset OTP')], default='LOGIN', max_length=20),
        ),
    ]
