# Generated by Django 3.2.25 on 2026-01-27 19:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admin_basic', '0003_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('source', models.CharField(choices=[('web', 'Web'), ('service', 'Service'), ('product', 'Product')], default='web', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Enquiry',
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
