# Generated by Django 3.2.25 on 2026-01-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_basic', '0004_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique setting identifier', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Display name for the setting', max_length=200)),
                ('value', models.TextField(help_text='Setting value')),
                ('setting_type', models.CharField(choices=[('TEXT', 'Text'), ('TEXTAREA', 'Text Area'), ('BOOLEAN', 'Boolean'), ('IMAGE', 'Image'), ('EMAIL', 'Email'), ('URL', 'URL')], default='TEXT', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of the setting')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Setting',
                'verbose_name_plural': 'Global Settings',
                'ordering': ['name'],
            },
        ),
    ]
