# Generated by Django 3.2.25 on 2026-01-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='description',
        ),
        migrations.AddField(
            model_name='gallery',
            name='category',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
    ]
