# Generated by Django 3.2.25 on 2026-01-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='features',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
