# Generated by Django 3.2.25 on 2026-01-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_package_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='features',
            field=models.TextField(default='[]', blank=True),
        ),
    ]
