# Generated by Django 3.2.25 on 2026-01-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_auto_20260128_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='duration_months',
        ),
        migrations.RemoveField(
            model_name='package',
            name='is_popular',
        ),
        migrations.RemoveField(
            model_name='package',
            name='slug',
        ),
        migrations.AlterField(
            model_name='package',
            name='features',
            field=models.TextField(default='[]', blank=True),  # Store features as JSON string
        ),
    ]
