# Generated by Django 3.2.25 on 2026-01-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_auto_20260128_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='features',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
